export const environment = {
  production: true,
  apiUrl: import.meta.env['NG_APP_API_URL'],
  commercetools: {
    projectKey: import.meta.env['NG_APP_PROJECT_KEY'],
    clientId: import.meta.env['NG_APP_CLIENT_ID'],
    clientSecret: import.meta.env['NG_APP_CLIENT_SECRET'],
    region: 'europe-west1.gcp',
    apiUrl: 'https://api.europe-west1.gcp.commercetools.com',
    authUrl: 'https://auth.europe-west1.gcp.commercetools.com',
    scopes: [
      // TODO: keep only necessary scopes
      `manage_orders:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `manage_order_edits:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `manage_sessions:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `manage_shopping_lists:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `manage_customers:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_types:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_product_selections:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_categories:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_shipping_methods:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_project_settings:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_cart_discounts:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_discount_codes:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_sessions:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_tax_categories:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_standalone_prices:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_products:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_published_products:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `view_published_products:${import.meta.env['NG_APP_PROJECT_KEY']}`,
      `create_anonymous_token:${import.meta.env['NG_APP_PROJECT_KEY']}`,
    ],
  },
  LOCAL_STORAGE_KEYS: {
    customerId: 'customerId',
    accessToken: 'accessToken',
    refreshToken: 'refreshToken',
    anonymousToken: 'anonymousToken',
    anonymousId: 'anonymousId',
    user: 'user',
  },
};
